README.md, ios/GitPoint.xcodeproj/project.pbxproj, package.json
Really basic npm scripts & README file that outlines how to build & run.
=> npm scripts to build & run

android/app/src/main/AndroidManifest.xml
This fixes one of the initial issues on Android.
=> Deep Linking fix for Android

routes.js
This moves the tab bar to the bottom on Android.
=> Move tab bar to the bottom

src/api/index.js
Make it clear (in the code) that these API keys are for development and not for the real app.
=> 📝 Document development API keys

src/api/index.js, src/components/repository-list-item.component.js, src/user/user.action.js
Screenshot for repo list of the authenticated user.
=> show private repositories. Closes #15

ios/GitPoint.xcodeproj/project.pbxproj, ios/GitPoint/Info.plist
Fixed #37.
Thanks for the awesome project!
=> iPad support

src/components/user-profile.component.js
Caused by adding private repos that aren't loaded yet.
=> Hide NaN while waiting for private repos. Closes #64

package.json, root.store.js, src/components/index.js, src/components/search-bar.component.android.js, src/components/search-bar.component.ios.js, src/issue/screens/issue-settings.screen.js, src/issue/screens/pull-merge.screen.js, src/repository/screens/issue-list.screen.js, src/repository/screens/pull-list.screen.js, src/repository/screens/repository.screen.js, src/search/screens/search.screen.js, src/user/screens/profile.screen.js, src/user/screens/repository-list.screen.js, yarn.lock
Hey @housseindjirdeh , really sorry for the late reply. 
I found you've merged #49, however there have several eslint errors & javascript errors. 
So I open this PR, trying to solve them. Please help to review this again, thanks!
=> Fixed merge bugs

src/user/user.action.js
=> Don't include other user repos that I have push access to

src/auth/screens/auth-profile.screen.js, src/components/entity-info.component.js, src/components/index.js, src/organization/screens/organization-profile.screen.js, src/user/screens/profile.screen.js
*mentioned in https://github.com/gitpoint/git-point/issues/17#issuecomment-314650595*
User profile:
Organization:
=> Add location to profiles

src/user/user.action.js
=> Include forks when search in user repo list

package.json, src/components/comment-list-item.component.js, yarn.lock
I also submitted a PR to `react-native-htmlview` but it didn't pass the CI test and there are some old ones not merged...
So this quick fix will works for us 👍
=> Fix <li> prefix number on ordered list (<ol>) #92

src/notifications/screens/notifications.screen.js, src/search/screens/search.screen.js
=> Header enhancements for Notifications and Search screens

src/search/screens/search.screen.js
=> Remove listContainer border while it's loading

src/components/repository-profile.component.js
Finally positioned top-centered 😄  
Android and iOS preview:
----
=> Main language in Repository view. Close #119

src/components/repository-profile.component.js, src/components/repository-section-title.component.js, src/repository/screens/issue-list.screen.js, src/repository/screens/pull-list.screen.js, src/repository/screens/repository.screen.js
- Fixed issues and pull requests header
- Hid language dot icon while it's loading
=> Small UI fixes

routes.js, src/auth/screens/auth-profile.screen.js, src/auth/screens/index.js, src/auth/screens/privacy-policy.screen.js
Adds a privacy policy screen :dancer:
=> add privacy policy

package.json, src/auth/screens/login.screen.js, src/config/colors.js, yarn.lock
Adds onboarding swiper. Closes #51.
=> Onboarding swiper

routes.js, src/api/index.js, src/issue/issue.action.js, src/issue/issue.reducer.js, src/issue/issue.type.js, src/issue/screens/index.js, src/issue/screens/new-issue.screen.js, src/repository/screens/issue-list.screen.js, src/repository/screens/repository.screen.js
Here is the **submit new issue** (#58) PR.
> Currently `WIP`.
=> Submit new issue (closes #58)

src/auth/auth.action.js, src/auth/screens/auth-profile.screen.js, src/auth/screens/login.screen.js, src/auth/screens/splash.screen.js, src/auth/screens/welcome.screen.js, src/config/colors.js, src/utils/method-helpers.js
Closes #181. Updates welcome screen so user is automatically navigated when request finishes firing:
Also:
* improved colors used in onboarding swiper
* created a `resetNavigationTo` helper method to simplify things
=> update welcome screen, change onboarding swiper colors slightly

src/components/members.component.js, src/locale/languages/en.js, src/repository/repository.reducer.js, src/repository/screens/repository.screen.js
=> Show message if no contributors found

src/auth/screens/events.screen.js
Closes #200.
Before | After 
| - | -
=> Align event text

src/components/entity-info.component.js
Tested on Android only as I didn't succeed in running it on iOS (See #29)
=> fix(share): stop pre-filling email subject

src/locale/languages/en.js, src/repository/screens/pull-list.screen.js
This PR fixes an Issue in the `pull-list.screen.js`
See below.
But this needs to be done than to every language file in the future.
Its probably just a copy/paste mistake.
Its my first PR so please give me any feedback you have! 😄 
I will add myself to the contributors list with my next PR with german translation.
=> fix(localization): pull-list.screen.js copy/paste mistake

src/repository/screens/repository.screen.js
=> fix(repository): Swap watch and share actions

src/components/comment-input.component.js, src/issue/screens/issue.screen.js
Fixes #206.
**Need to check on iOS**. There I understand, there was no such problem?
=> fix(comment): allow new lines in comments on Android

src/repository/screens/repository.screen.js
=> fix(repo): hide issues section in forked repo

src/auth/screens/events.screen.js
=> fix(events): Fix wrong wording for commented on pull request

src/components/user-profile.component.js
Gives GitPoint an additional chance of refreshing an updated profile picture
Close #265
=> fix(profile): prepend user.updated_at to avatar url

src/locale/languages/en.js
`searchMessage` should be "Search for any {{type}}" instead of "Searching for any {{type}}"
=> fix(locale): Update en.js

src/locale/languages/nl.js
Some minor modifications in the NL translation file.
=> refactor(translation): minor nl changes

src/user/screens/follower-list.screen.js, src/user/screens/profile.screen.js, src/user/user.action.js, src/user/user.reducer.js, src/user/user.type.js
=> fix(profile): fix the wrong `follows you` badge

src/api/index.js, src/components/user-profile.component.js, src/issue/screens/issue.screen.js, src/organization/screens/organization-profile.screen.js
1. At first, I just want to fix the wrong usage of `Promise.all`, which causes the refresh state is not updated at the right time.
2. Then the console reminds me that `getContributorsByDispatch` is undefined.
3. And I found the organization profile can not be open correctly, even if running with `master` codes.
4. The last thing is that no need to show stars for organizations.
=> Fix Promise.all and related bugs

src/components/issue-list-item.component.js
- Show issue and pull request number in their list
Closed #298
=> add pr/issue number to list

src/auth/screens/auth-profile.screen.js, src/auth/screens/user-options.screen.js
As suggested in #292 for a better user experience.
=> feat(ux): Move check for updates into settings screen

android/app/src/main/AndroidManifest.xml, ios/GitPoint/Info.plist, src/components/parallax-scroll.component.js
I do not know, maybe it was so necessary, but I added support for landscape orientation. In this regard, we had to slightly change the parallax component , but everything seems to be fine.
=> feat(screen): add support for landscape orientation

src/api/index.js, src/repository/repository.action.js, src/repository/repository.reducer.js, src/repository/repository.type.js, src/repository/screens/repository.screen.js
@CameronSamuels  @machour Closed #309.
@housseindjirdeh  I can't understand the logic of `JSON.parse(readMe).message`, which was added by [67ec2b](https://github.com/gitpoint/git-point/commit/67ec2be2f79ce20e24412263a119cfba3cafa4aa#diff-092912c8c2f376745a57ba470acbf651) purposely. So I just keep it.
=> feat(repository): Hide readme button if no readme

package.json, root.store.js, yarn.lock
For better Redux debugging and for React Native Debugger application work https://github.com/jhen0409/react-native-debugger
=> chore(dev): add redux-devtools-extension

src/auth/screens/auth-profile.screen.js, src/auth/screens/events.screen.js, src/auth/screens/login.screen.js, src/auth/screens/user-options.screen.js, src/issue/screens/issue-settings.screen.js, src/issue/screens/issue.screen.js, src/issue/screens/new-issue.screen.js, src/issue/screens/pull-merge.screen.js, src/notifications/screens/notifications.screen.js, src/repository/screens/issue-list.screen.js, src/repository/screens/pull-list.screen.js, src/repository/screens/read-me.screen.js, src/repository/screens/repository-code-list.screen.js, src/repository/screens/repository-file.screen.js, src/repository/screens/repository.screen.js, src/search/screens/search.screen.js, src/user/screens/follower-list.screen.js, src/user/screens/following-list.screen.js, src/user/screens/profile.screen.js, src/user/screens/repository-list.screen.js
=> refactor(screens): switch to bindActionCreators style

package.json, src/components/markdown-htmlview.component.js, yarn.lock
=> fix(markdown): Make sure code is not HTML encoded

src/repository/repository.action.js, src/user/user.action.js
As @machour suggested in #335.
=> refactor(*): Update 2 other places of checking http status

package.json, yarn.lock
=> fix(photo): Upgrade react-native-photo-view to fix double zoom issue

src/auth/screens/language-settings.js, src/auth/screens/user-options.screen.js
=> feat(language-list): add emoji flags

src/notifications/screens/notifications.screen.js
This may not be entirely customary, if we do not have elements, then pull-to-refresh should not be, but in my opinion this will be a nice addition. 
Also, I even aligned the message "receiving notifications" in the center, so it seems to me better. Although it was required to determine the height (`saveContentBlockHeight`) and to set the height for the blocks to align, there may be a way to do without it, but I did not find.
Demo:
=> feat(notifications): add pull to refresh if notifications is empty

.gitignore
This is a small one for ignoring `vscode` + `idea`.
=> feat: ignore editors

src/components/repository-list-item.component.js
=> feat(repository-list-item): add forks count

README.md
This can help browser the document faster and easier!
=> docs(readme): add table of contents section

README.md, package.json
=> docs(readme): integrate doctoc package to update Table of Contents

src/components/comment-list-item.component.js
As we discussed on Gitter, for some users, this type of event could be annoying, so this PR removes this event.
=> feat(issue_comments): Remove long press event

src/api/index.js, src/issue/issue.action.js, src/issue/issue.reducer.js
we need both comment.body & comment.body_html to handle comments editing using markdown
=> fix(api): Implement and use Accept FULL for comments

src/locale/languages/fr.js
Translated english strings.
Other languages still need to be updated!
=> chore: update french translations

src/components/issue-list-item.component.js, src/locale/languages/en.js, src/locale/languages/fr.js, src/locale/languages/nl.js, src/locale/languages/pt-br.js, src/locale/languages/ru.js, src/locale/languages/tr.js
- Before:
- After:
The subtitle seems to be changed a little, because its original styles are provided by `react-native-elements`. Now in order to use custom subtitle, I set them based on our constants.
I am not very good at UI design. Waiting for your suggestions. :)
=> feat(issue): Show issues author and comments count

src/auth/screens/auth-profile.screen.js, src/components/user-profile.component.js, src/user/screens/profile.screen.js
The last final part :smile: 
Based on #414 (it too was closed too early, so I had to create a new PR)
=> refactor(profiles): simplify check of fully loaded user data

src/locale/languages/fr.js, src/locale/languages/nl.js, src/locale/languages/tr.js
Following up on #408, this PR will update the remaining translations.
Still waiting on `nl`
- Update TR translations. Thanks goes to @abdurrahmanekr
=> chore: Update remaining translations

android/app/build.gradle
=> chore(android): Compile animated gifs support

CONTRIBUTING.md, README.md
Hey guys,
a small fix because we moved all contributors to a new file, a link in CONTRIBUTING.md was wrong.
❤️
=> fix(contributors): fix link location for contributors

package.json, src/components/mention-area.component.js, yarn.lock
Adds fuzzysearch npm module which has a nicer and clean api for autocomplete.
=> refactor: Adds fuzzysearch

src/notifications/screens/notifications.screen.js
=> refactor: Use an enum for notifications type

src/auth/screens/login.screen.js
Gives an additional chance to bypass caching issues on Android with WebView
=> fix: Update stateRandom and reset cookies after a successful login

src/components/notification-icon.component.js
Convert notification-icon.component.js to use styled-components as part of #503
=> chore(*): convert notification icon styles to styled-component

src/components/label-list-item.component.js
Converted the label-list-item component styles to styled-components for #503
=> chore(*): convert label-list-item component styles to styled component

src/components/github-htmlview.component.js
For example, when you visit #479.
=> feat(markdown): Support to render del tag

src/components/issue-event-list-item.component.js
Fixed an inversion line 260.
#PrettierDidTheRest
=> fix(issue-events): Fix inverted label for deleted/restored this branch

src/components/entity-info.component.js
=> refactor: use styled-components in entity-info

src/components/badge.component.js
This was breaking `master` for 1.4
Related to #569
=> fix(build): fix styled components errors

src/components/entity-info.component.js
=> fix(entity-info): fix typo in prop name

__tests__/tests/components/UserProfile.js, src/components/user-profile.component.js
This Fixes #570 `v1.4`.
I updated our unit tests so this won't happen again (hopefully).
=> fix(user-profile-component): Fix user profile image

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/PULL_REQUEST_TEMPLATE.md
=> docs: add issues/pulls templates

src/components/mention-area.component.js
| Version?         | v1.3.0      |
| Devices tested?  | iPhone 7 simulator |
| Related ticket?  |        |
---
App was crashing when you mention someone in an issue. Updating `fontsize` style prop into `font-size` fixes the issue.
=> fix: Mention area component fontSize prop

src/auth/screens/auth-profile.screen.js, src/user/screens/profile.screen.js
| Devices tested?  | Android version Nougat |
| Related ticket?  | #569         |
---
| ![beforeauth](https://user-images.githubusercontent.com/1559013/32139635-4a592116-bc25-11e7-91ab-981d1a2c2083.png) | ![subtitlewithfontweight](https://user-images.githubusercontent.com/1559013/32139637-5ee3f8e0-bc25-11e7-9039-9c4b8fd7a3c4.png) |
After the react-native-elements update, we've lost some styles,
this commit removes ellipsize from bio text and set `fontWeight` to normal.
I'm still using the text as subtitle but we …
=> fix(ui): Fix Bio section in auth-profile

src/components/comment-input.component.js
| Version?         | master     |
| Devices tested?  | iPhone 7, Android Nexus (simulators) |
| Related ticket?  | #536       |
Android had a flickering problem when height started with 0.
Also adapted the height a bit more for the final input.
=> fix(comment-input): Fix the input text being chopped up

README.md
Earlier this month we received licenses for free use of IDE's from JetBrains, I think it worth mentioning this and add a note that the new members of the organization (active contributors) can get it.
=> docs: add acknowledgments section

README.md
Remove codesponsor.io, as the service is [shutting down](http://mailchi.mp/f9b57b5ea377/code-sponsor-is-shutting-down-on-december-8) 😞
=> docs: remove codesponsor.io

App.js, src/auth/screens/login.screen.js, src/components/view-container.component.js, src/config/index.js, src/config/status-bar.js
| Version?         | v1.3.1      |
| Devices tested?  | iPhone iOS 11, Android 7 |
| Related ticket?  | #4       |
---
| ![beforedynamic](https://user-images.githubusercontent.com/1559013/32822025-46dddade-c9b5-11e7-96dc-30e263dbf31f.gif) | ![afterdynamic](https://user-images.githubusercontent.com/1559013/32822046-6510c4c6-c9b5-11e7-9341-b246e658eb7c.gif) |
| <img width="280" alt="screen shot 2017-11-15 at 03 34 58" src="https://user-images.githubusercontent.com/1559013/32822245-56600a8a-c9b6-11e7-824c-6e05a08ec105.png"> | <img width="280" …
=> fix: Dynamic status bar

ios/GitPoint.xcodeproj/project.pbxproj
A small annoying thing, is that whenever I compile the project, `project.pbxproj` is marked a modified in GIT.
I'm wondering if I'm the only one experiencing this 🤔
=> chore: update project.pbxproj

src/auth/screens/auth-profile.screen.js, src/auth/screens/user-options.screen.js, src/components/section-list.component.js, src/notifications/screens/notifications.screen.js, src/user/screens/profile.screen.js
| Devices tested?  | iPhone 6s/Android Nexus |
| Bug fix?         | yes/**no**      |
| New feature?     | yes/**no**      |
| Includes tests?  | yes/**no**      |
| All Tests pass?  | **yes**/no      |
---
| ![before](https://user-images.githubusercontent.com/12476932/33866730-548f51fa-dec6-11e7-9e9d-babd5655da54.png) | ![after](https://user-images.githubusercontent.com/12476932/33866715-366618a8-dec6-11e7-98e6-53ac5e5864cb.png)
| ![before](https://user-images.githubusercontent.com/12476932/33866752-768b8b98-dec6-11e7-8336-931b3b293388.png) | ![after](https://user-images.githubusercontent.com/12476932/33866762-84834088-dec6-11e7-937f-9532 …
=> style(*): Minor style updates

src/locale/languages/es.js
| Devices tested?  | simulator |
---
|![before](https://user-images.githubusercontent.com/11599942/34909864-365ef93a-f8aa-11e7-9d6c-5ef0e3001ae8.png)|![after](https://user-images.githubusercontent.com/11599942/34909875-4d65fac0-f8aa-11e7-8260-f4b0802cbad0.png)|
Change Spanish "unreadButton" translation.
=> fix(locale): change es translation

package.json, yarn.lock
| Version?         | dev-master      |
| Devices tested?  | iPhone 7, Android Nexus 5 |
Switched back to the original react-native-parallax-scroll-view package as latest version support React 16
=> chore: back to react-native-parallax-scroll-view (supports React 16)

src/locale/languages/de.js
Just a typo fix in the german language file.
=> chore: fix typo in german language

src/components/issue-event-list-item.component.js, src/issue/screens/issue.screen.js
| Related ticket?  | #714         |
---
| After    |
| -------------- |
|![git-point-fix](https://user-images.githubusercontent.com/1736154/36088530-9bfc3b66-1012-11e8-854d-b467a47e5991.jpg)|
Check `event.requested_reviewer` and `event.requested_team`. The `event` doesn't contain enough information about the team, so I passed `repository` from the outside.
=> fix(issue): Fix requested review to a team

src/components/label-button.component.js
---
|![6 pic](https://user-images.githubusercontent.com/1736154/36191930-6e6b6972-119a-11e8-89b3-d3b21279dd74.jpg)|![8 pic](https://user-images.githubusercontent.com/1736154/36192100-1f4cd9ba-119b-11e8-8ee6-3bafe909a21e.jpg)|
Migrate `label-button.component.js` to styled-components.
=> chore(label): Migrate LabelButton

src/api/client.js
Removed a leftover from a refactoring made before proposing the new API.
=> fix: remove unnecessary calls

src/organization/screens/organization-profile.screen.js
---
|  ![simulator screen shot - iphone 6 - 2018-04-02 at 17 28 14](https://user-images.githubusercontent.com/304450/38205724-80c97436-369f-11e8-8ddb-5e2d99f0c6b1.png) |![simulator screen shot - iphone 6 - 2018-04-02 at 17 58 04](https://user-images.githubusercontent.com/304450/38205699-6b22c2e0-369f-11e8-92e9-a3928f4b870e.png)|
Fixed the org description that was truncated
=> fix(ui): don't truncate org description

src/components/loading-indicators/loading-event-list-item.component.js
| Related ticket?  | #765        |
---
|<img width="375" alt="2018-04-22 6 19 13" src="https://user-images.githubusercontent.com/1736154/39094025-a23e3be4-465b-11e8-9fb0-975de355504c.png">|<img width="378" alt="2018-04-22 6 16 01" src="https://user-images.githubusercontent.com/1736154/39094023-9f07a41a-465b-11e8-844f-dfbd77b8e382.png">|
@machour Sorry for my late response of #765. Everything is OK, except for a little problem of UI styles and code styles.
According to …
=> fix(loading): Fix margins of loading event list item

.gitignore, ios/GitPoint.xcodeproj/project.pbxproj
| Includes tests?  | no     |
| Related ticket?  | #780        |
---
Rolled back `ip.txt` related changes.
Closes #780
=> chore: revert changes regarding ip.txt

src/auth/screens/login.screen.js
| Devices tested?  | iPhone 7|
---
|![simulator screen shot - iphone 6s - 2018-04-23 at 21 00 44](https://user-images.githubusercontent.com/304450/39171660-704439c6-4797-11e8-8474-ac9e70e4b78f.png)|![simulator screen shot - iphone 6s - 2018-04-24 at 08 11 02](https://user-images.githubusercontent.com/304450/39171666-712ab266-4797-11e8-9033-e5e41aa31c61.png)|
|![simulator screen shot - iphone 6s - 2018-04-23 at 21 00 48](https://user-images.githubusercontent.com/304450/39171661-706e0 …
=> refactor: switch LoginScreen to styled components

src/auth/screens/events.screen.js
refactored `getIcon()` to keep the code tight
=> refactor(events): simplify icons code

src/locale/languages/de.js
Fixed some typos and add a snippet.
=> Fix some typos

src/locale/languages/zhCn.js
| Version?         | v1.5.0      |
| Devices tested?  | no|
| Bug fix?         | no |
| All Tests pass?  |       |
| Related ticket?  |       |
---
"follows you" should be "已关注你" , not "你已关注", in zh_cn
=> fix:correct 'follows you' zh_cn translate

src/components/repository-profile.component.js
| Devices tested?  | iPhone X... |
---
Before
After
Adjust repo language label's top position of RepositoryProfile component for iphoneX
=> fix: adjust language label top position in RepositoryProfile for ipX

__tests__/tests/utilities/action-helpers.js
Hey,
There is an update for action-helpers.
=> Add tests for Action Helper (#518)

__tests__/tests/reducers/organization.reducer.js, src/organization/organization.reducer.js
| Version?         | -      |
| Devices tested?  | - |
| Related ticket?  | #518       |
---
none
Add tests for organization reducer
=> test: add tests for organization reducer (#518)

__tests__/tests/reducers/repository.reducer.js, src/repository/repository.reducer.js
#518
| Version?         | -     |
| Devices tested?  | - |
| Related ticket?  | #518        |
---
None
Add tests for repository.reducer.js
=> test(repository.reducer.js): Add tests for repository reducer

.eslintrc, .flowconfig, src/api/client.js, src/api/proxies/create-dispatch-proxy.js
| Devices tested?  | iPhone 6 Plus Simulator |
| Related ticket?  | /        |
---
Although we didn't rely too much on flow, I tried to fix some errors when running `yarn run flow-status`.
=> fix(flow): fix flow errors

src/components/loading-indicators/loading-repository-profile.component.js
| Devices tested?  | iPhone 6 (iOS 10.3) |
| Related ticket?  | #532      |
---
Migrated LoadingRepositoryProfile to styled-components
=> refactor: switch LoadingRepositoryProfile to styled components

__tests__/tests/components/ViewContainer.js, src/components/view-container.component.js
| Devices tested?  | n/a |
| Related ticket?  | #518       |
---
=> test(view-component): add tests for view-component

src/locale/languages/ptBr.js
| Devices tested?  | none |
| Bug fix?         | no |
| New feature?     | no |
| Includes tests?  | no |
| All Tests pass?  | - |
| Related ticket?  | - |
=> Portuguese translation

src/locale/languages/ru.js
#439
| Devices tested?  | none|
| All Tests pass?  | -      |
| Related ticket?  | #439        |
---
Added some small corrections to the Russian translation.
The translation is otherwise really well done :)
=> fix: Add (very) small corrections to the Russian translation :)

src/components/loading-indicators/loading-repository-list-item.component.js
| Devices tested?  | iPhone 6 (iOS 10.3) |
---
|![before](https://user-images.githubusercontent.com/6077433/47423112-e1a20b80-d7a1-11e8-8446-f57c71c778c5.png)|![after](https://user-images.githubusercontent.com/6077433/47423126-e9fa4680-d7a1-11e8-9c55-d9a677da4d97.png)|
Migrated LoadingRepositoryList to styled-components
=> Migrated LoadingRepositoryList to styled-components

src/components/loading-indicators/loading-members-list.component.js
| Devices tested?  | iPhone 6 (iOS 10.3) |
---
|![before](https://user-images.githubusercontent.com/6077433/47420538-507c6600-d79c-11e8-8488-b66746cfde86.png)|![after](https://user-images.githubusercontent.com/6077433/47420549-56724700-d79c-11e8-87ec-117066ed1c15.png)|
Migrated LoadingMembersList to styled-components
=> refactor: switch LoadingMembersList to styled components

src/locale/languages/zhCn.js
| Devices tested?  | Samsung Galaxy S7 |
| Related ticket?  | no ticket available        |
---
Simplified Chinese translation for unable to login was missing, this has now been added.
=> MIssing can't login translation

src/api/schemas/gql-repos.js, src/issue/screens/issue.screen.js, src/repository/screens/repository.screen.js
| Version?         | v1.6.0     |
| All Tests pass?  | yes |
| Related ticket?  | #853        |
---
| Fixed Repo   | Fixed Issue    |
|![fixed](https://user-images.githubusercontent.com/1736154/49326831-ed4bd380-f592-11e8-8e26-ad7d7de4b4ba.png)|![fixed-issue](https://user-images.githubusercontent.com/1736154/49326830-ecb33d00-f592-11e8-8aae-bd1a1a18c6a9.png)|
As explained in #853,
1. wrong entity name was used, which resulted in no repository was founded.
```
// src/api/proxies/create-dispatch-proxy.js#L148, 
const entity = getState().entities[type][id]; …
```
=> fix(repo): fix regressions of staring repository and viewing issues by deleted users

src/components/issue-event-list-item.component.js, yarn.lock
| Devices tested?  | iPhone 7... |
| Bug fix?         | yes/no      |
| New feature?     | yes/no      |
| Includes tests?  | yes/no      |
| All Tests pass?  | yes/no      |
---
|![before](https://user-images.githubusercontent.com/9524411/50447123-0d816f00-0954-11e9-86d1-226d60ef5a28.png)|![after](https://user-images.githubusercontent.com/9524411/50447077-bf6c6b80-0953-11e9-87db-cce2a91aa148.png)
=> feat: add reviewed type pull request event

__tests__/tests/components/IssueListItem.js
| Version?         |      |
| Devices tested?  |  |
| Related ticket?  | #518        |
Add missing test for IssuListItem component
=> Add IssueListItem component tests

src/locale/languages/it.js, src/locale/languages/pt.js, src/locale/languages/ptBr.js
| Version?         |  |
| Devices tested?  | |
| Related ticket?  |         |
---
Some translation keys for **ptBr** updated.
=> fix: Update locale text for pt-Br

__tests__/tests/components/UserListItem.js, src/components/user-list-item.component.js
| Version?         |    |
| Devices tested?  | |
| Includes tests?  | yes     |
| Related ticket?  | #518        |
Add test for `UserListItem` component.
=> test: Add UserListItem component tests

__tests__/tests/components/Button.js
re #518
| Devices tested?  | iPhone 7... |
| Bug fix?         | yes/no      |
| New feature?     | yes/no      |
| Includes tests?  | yes/no      |
| All Tests pass?  | yes/no      |
---
|![before](http://placekitten.com/700/1000)|![after](http://placekitten.com/700/1001)|
Adding test case for button component
=> test(button test): add assert check if Button without title

App.js, android/app/build.gradle, android/app/src/main/java/com/gitpoint/MainApplication.java, android/settings.gradle, ios/GitPoint.xcodeproj/project.pbxproj, package.json, src/auth/screens/auth-profile.screen.js, src/auth/screens/login.screen.js, src/auth/screens/welcome.screen.js, src/config/status-bar.js, src/notifications/screens/notifications.screen.js, src/organization/screens/organization-profile.screen.js, src/repository/screens/repository.screen.js, src/search/screens/search.screen.js, src/user/screens/profile.screen.js, yarn.lock
| Version?         | v1.7.1      |
| Devices tested?  | iPhone 6/Xʀ, Nexus 5X, Pixel 3 XL |
| Related ticket?  | #884, 8839062, 5bdd37e, 161bd78       |
---
| Nexus 5X (no notch)   | Pixel 3 XL (with notch)    |
|![nexus](https://user-images.githubusercontent.com/1736154/68226261-bac11b00-002c-11ea-9592-d0470fba9e04.jpg)|![pixel](https://user-images.githubusercontent.com/1736154/68226294-c9a7cd80-002c-11ea-80fa-e6462b4e8c0f.jpg)|
|![nexus3](https://user-images.githubusercontent.com/1736154/68226286-c1e82900-002c-11ea-8bc0-31d026dc4006.jpg)|![pixel3](https://user-images.gith …
=> fix: provide real safe area view

__tests__/tests/actions/organization.action.js, __tests__/tests/actions/repository.action.js, package.json, yarn.lock
| Version?         |       |
| Devices tested?  |  |
| Includes tests?  | yes     |
| Related ticket?  | #518         |
Add test for repository and organization actions.
=> test: Add repository and organization actions tests
