- README.md
- yarn.lock
Auto update for contributors were broken because we were using an `<img>` instead of markdown, this should fix it + I ran `yarn install` and got some updates.
The readme will ended up looking like this
> update contributors badge + deps

- src/components/code-line.component.js
- src/repository/screens/pull-diff.screen.js
> Will be great to have syntax highlighting on `PullDiffScreen` for pull requests
As @housseindjirdeh said here : https://github.com/gitpoint/git-point/pull/60#issuecomment-315512222 
So this PR is about this integration.  
Screenshots:
Because of how each line are generated (separately), there is a "Syntax Highlighter" on each line. I did some performance tests to show you that it's not very slower than before (but, yes it is! Especially in case of a lot of line diff).
| | Before | Now | |
|:-:|:-:|:-:|:-:|
| PR #49 | 2480 ms | 4090 ms | +64% |
| PR #79 | 700 ms | 1010 ms | +27% |
_Tested on my iPhone 6S and a "manual chronometer" (human imprecision)_
> Syntax highlighting in PR Diff

- CONTRIBUTING.md
- README.md
- package.json
- yarn.lock
As an alternative to the two commands: `yarn start` + `yarn run android|ios`, instead just run `yarn start: android` or `yarn start:ios` - you do not need to run two terminals. Quickly and convenient.
Can I add the appropriate commands with `logger`?
> Add npm scripts for quick develop

- .babelrc
- package.json
- src/auth/screens/auth-profile.screen.js
Now the version of the application is hardcoded, which is not good, it's best practice to specify the version number in the `package.json` file and from there take it to display.
> Show actual version of the application

- src/auth/screens/auth-profile.screen.js
- src/components/entity-info.component.js
- src/organization/screens/organization-profile.screen.js
- src/user/screens/profile.screen.js
Adds company to user profile (and auth user profile)
I show the listitem chevron and make it navigate to an organization if and only if there's an `@` before the company _and_ the company is within the user's organizations
> add company to profile + auth profile, closes #140

- src/components/repository-profile.component.js
These are small bits of UI improvement related to #114 😄 
This is how the long title looks like with changes:
I've changed the margin left & right to `30` and instead of truncating string programatically decided to use `numberOfLines` props of `Text`.
> Better UI for long repository description;

- android/app/build.gradle
- android/app/src/main/java/com/gitpoint/MainApplication.java
- android/settings.gradle
- ios/GitPoint.xcodeproj/project.pbxproj
- package.json
- src/components/image-zoom.component.js
- src/components/index.js
- src/components/user-profile.component.js
- yarn.lock
When clicking on the avatar, the full size of the picture opens in the modal window (closes #7).
Important note: I tested the work only on Android, **please see how it works on iOS**.
Also considered the use of the library:
[react-native-lightbox](https://github.com/oblador/react-native-lightbox) - slows opening on Android
[react-native-zoom-image](https://github.com/Tinysymphony/react-native-zoom-image ) - works fine, but does not apply to miniature styles (`borderRadius` in particular)
Therefore, I had to make my own component, using the built-in component `Modal` and PhotoView.
> [WIP] Opening the profile avatar in full size by click. Closes #7

- src/auth/screens/events.screen.js
I noticed that the 'Member' events were not rendered/displayed correctly. It didn't show the repository the user was added to.
This is how it looks with the fix:
Which is in the same style as Github shows it.
> Render member events properly

- src/components/repository-section-title.component.js
- src/components/section-list.component.js
- src/repository/screens/repository.screen.js
It will fix this
From GitPoint repo and then open another repo, the contributors from previous repo will retain atleast 1 second and then update it.
> Hide some elements while repo is still loading

- src/issue/issue.action.js
- src/issue/screens/issue.screen.js
1. Issues don't load correctly from any screen except notifications screen
2. Pull request issues usually generate their `diff` before the issue is completely retrieved from `getIssueFromUrl`, moved method to actions file to only happen after issue is obtained
This PR fixes both
> fix issue loading from events screen + repository screens, fixes pull diff rendering

- src/components/code-line.component.js
- src/config/fonts.js
- src/repository/screens/repository-file.screen.js
This one should apply `Menlo` font to code preview. It also fix a typo with `OpenSans` declaration.
I said **should** because I can't see a big difference on my screen...
> Android fonts - Fix #121

- src/user/user.action.js
Quick fix: when moving to the organization's repositories there is nothing (it broke after the changes in [this commit](https://github.com/gitpoint/git-point/commit/0eb5fd9429e1865447278b4640c1aebb33729487))
Strangely, I do not see that API returns `permissions` for repos.
1. ![image](https://user-images.githubusercontent.com/4408379/28500369-cb006902-6fcf-11e7-8ab4-3dfe58254d17.png)
2. ![image](https://user-images.githubusercontent.com/4408379/28500375-ee455738-6fcf-11e7-9e74-77621d49ed8a.png)
> Fix displaying the list of organization's repositories

- package.json
- src/components/comment-list-item.component.js
- yarn.lock
In #118 I created an internal quickfix to the `react-native-htmlview` plugin. I also opened an issue in the plugin repo.
As I think it's better to use a global fix than an internal quickfix (:wink:) and as version `0.12` is out and fix this one, we should merge this one.
> Fix ordered-list 2/2

- package.json
`package.json` version was making `linter-staged` failed without any other error/stacktrace than:
```
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint-staged`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
```
When I added a `.0` to the version number, that allowed me to commit. 
I also tried to update `linter-staged` to 4.0.2 but it didn't fix the pre-commit hooks.
---
I found the error by running:
```
$ npm run lint-staged
npm ERR! Invalid version: "1.1"
npm ERR! A complete log of …
```
> Fix pre-commit lint-staged warning/error

- routes.js
- src/notifications/screens/notifications.screen.js
Now the notification item have this title:
There is no number and type (issue or PR). So I thought it would be nice to add this:
> Add number and type notification to title

- src/repository/screens/repository.screen.js
- Added a 'share' action to the actionsheet on the repository screenshot. This uses the native share window, so you have all your available options shown. See the screenshots. (My simulator only has twitter) 
I added the actual repository link to the message, so its visible to the user that it also shares the url. If the `url` key is used in the share method it doesn't show the url. I thought that it might be strange for the user. 
- Removed unicode star. Since we don't have the octicons in the actionsheet yet, i removed the star since it doesn't look good otherwise.
> Feature: Share repository

- src/auth/screens/events.screen.js
- src/components/issue-list-item.component.js
Earlier in #160 this was fixed for the notification screen, the current PR sets the correct titles for all other (events and issue list component).
> Set correct issue titles

- commitlint.config.js
- commitlint/index.js
- package.json
- yarn.lock
Fixes #190
This adds a git hook for commit message linting. Also uses `husky` instead of `pre-commit` for git hooks because commit message linting requires the `commit-msg` hook.
Commit message requirements:
- Present tense imperative
- No period in subject
- < 72 characters (for subject)
- Blank line between subject and body (pretty standard)
- In the format: `type(scope): description` or `type: description` if no scope
- Type can be one of:
- `build` for changes to the build system
- `chore` for releases, dependency updates and other general chores
- `docs` for documentation changes
- `feat` for feature additions (reference the issue # in the body)
- `fix` for bug fixes (reference the issue # in the body)
- `perf` for performance boosts
- `refactor` for code refactors
- `revert` for …
> test(hooks): add commit message linting

- src/components/entity-info.component.js
Prevent render EntityInfo component if there is nothing to show (eg [github-beta](https://github.com/github-beta)).
Before | After
| - | - |
> Not show title "Info" if there is not any information to display

- routes.js
- src/components/comment-list-item.component.js
- src/components/members.component.js
- src/issue/screens/issue.screen.js
Now the screen auth profile can only be when navigating from the tabbar, although it is displayed for the current user from other places: if the user is on the organization list, if it is mentioned in the issue description or in its comments. Of all these places user should be navigated **not** to the normal profile screen, but to the auth profile.
From this follows such a problem that I can _follow myself_ (:rofl:), or again, organizations will not all be displayed.
> Navigate to auth profile screen for the current user

- package.json
- root.store.js
- src/config/reactotron.js
- yarn.lock
Please refer this project: [reactotron](https://github.com/infinitered/reactotron).
Reactotron is cross-platform react/react-native inspector.
It might be helpful when developing. We can see not only the redux actions, store structure & content, but also the API response (including response content/header & request header) in our app.
Screenshots:
- API Response:
(If we want to see the network response content, it need to turn off the debug mode. Seems their bug.)
- store:
> chore(dev): add reactotron for inspection

- README.md
Any improvements is welcome, because English (as you probably all noticed :laughing: ), unfortunately, is not my native language.
> docs(README.md): add translation instruction

- CONTRIBUTING.md
Improved word choice and sentence structure.
> docs: improve word choice

- src/components/repository-list-item.component.js
> fix(repo): Show repo prefix for search repo result

- routes.js
- src/issue/screens/new-issue.screen.js
Also give ability to add new line in the issue body
> fix(new-issue): various submit new issue improvement

- package.json
- src/auth/screens/login.screen.js
- yarn.lock
Unfortunately after updating React Native to 0.47.1 in PR #208, stopped working `onboarding swiper` (#174). I noticed this just now, because I left from  the GitHub account. And since the application has not been updated in the App Store/Google Play for a month, then this problem has not been detected, so we need to update the application _more often_ to detect such problems as quickly as possible.
On Android does not applies the background color (screenshot below), issue was [created](https://github.com/leecade/react-native-swiper/issues/511), but so far it has not been fixed and it is not known when it will be fixed. 
Therefore, I propose to replace the `react-native-swiper` component with the `react-native-app-intro`. All looks also, except for the sizes of dots, they are a little …
> refactor(onboarding-swiper): replace component

- src/api/index.js
- src/locale/languages/en.js
- src/locale/languages/fr.js
- src/locale/languages/nl.js
- src/locale/languages/tr.js
- src/utils/text-helper.js
First, now one digit after the decimal point is shown (instead of `1.33k` there will be `1.3k`, as on GitHub). And also improved the formatting algorithm, which excludes the output of zero after the comma (for example, earlier for the number 1005 was formatted as `1.0k`, now it will be just `1k`).
Secondly, localization is added.
And last, when fetching stars, this `abbreviateNumber` method is used.
> refactor(abbreviate numbers): improve algorithm, use localization

- src/components/repository-profile.component.js
I don't know what `watchers_count` means.
But in GitHub, `watch/star/fork` match `subscribers_count/stargazers_count/forks_count`.
> fix(repository): Fix the wrong watch count

- src/components/comment-list-item.component.js
It is an annoying bug if you click into some issues, like #298, which have empty body.
> RawText "" must be wrapped in an explicit <Text> component.
The reason is:
```
const commentPresent =
(comment.body_html && comment.body_html !== '') ||
(comment.body && comment.body !== '')
```
In most cases, `commentPresent` is boolean. But if `!comment.body_html && comment.body === ''`, it is an empty string.
> fix(issue): fix rawtext error if comment.body equals to empty string

- src/repository/screens/repository.screen.js
Closes #296 
| Before  | After |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/1559013/30356299-a0cdeb66-980e-11e7-9535-89d693e650ee.png"> | <img src="https://user-images.githubusercontent.com/1559013/30356294-9325015c-980e-11e7-802b-63071fea4bca.png"> |
> feat(repository): Show issues only when is enable

- src/api/index.js
- src/auth/screens/privacy-policy.screen.js
- src/components/issue-description.component.js
- src/issue/screens/issue.screen.js
- src/notifications/screens/notifications.screen.js
- src/repository/repository.action.js
> refactor(api): Always use api.root instead of hardcoding api url

- src/components/user-profile.component.js
- src/repository/screens/repository.screen.js
Fixes 2 small bugs while loading:
- The label "stars" in user profile is not kept in the same line with other labels.
- The "watching" badge in repository profile is not reset if the previous repository is watching.
> fix(ux): Fix user stars and repository watching status

- src/components/comment-input.component.js
- src/locale/languages/en.js
- src/locale/languages/fr.js
- src/locale/languages/nl.js
- src/locale/languages/pt-br.js
- src/locale/languages/tr.js
Now the send icon do nothing, although in many applications the message is sent by clicking on this icon, while the "Send" text is superfluous, so it was deleted. Now there is more free space for the text, which was the main point.
| Before | After
| - | -
| <img src="https://user-images.githubusercontent.com/4408379/30277482-98609f36-9710-11e7-85e1-87a415591d85.png" width="400"  /> | <img src="https://user-images.githubusercontent.com/4408379/30277481-9834b970-9710-11e7-9789-585b1090be57.png" width="400"  />
> feat(comment-input): submit comment on clicking on the icon instead text

- routes.js
There is a [possibility](https://github.com/react-community/react-navigation/blob/master/docs/api/navigators/TabNavigator.md#tabnavigatorconfig) to render tabs as necessary, this would be useful to us, because now the initial load takes a long time because there are many requests (notifications, profile).
However, I noticed one unpleasant thing for me: when lazy loading of tab, you can see a gray background for a few seconds, I can not understand where it comes from and whether it can be replaced with a loading indicator. Would be glad if someone else looked this up!
> feat(navigator): render tabs as needed

- src/api/index.js
- src/auth/auth.action.js
- src/auth/screens/privacy-policy.screen.js
- src/components/issue-description.component.js
- src/issue/issue.action.js
- src/issue/screens/issue.screen.js
- src/notifications/screens/notifications.screen.js
- src/organization/organization.action.js
- src/repository/repository.action.js
- src/user/user.action.js
While looking at redux, I came accros a few facts with api/index.js : 
- `fetch()` is being called in a lot of functions, inside and outside `api/index.js`. Some actions files also borrowed the accessTokenParameters* helpers.
- weird function naming: `fetchUrl` for GET returning json, and `fetchNormal` for GET returning a `Response`
- duplicate functions: `fetchUrlCommentsHTML` was in fact performing the exact same thing as `fetchUrl`
- code was piling up and the file was getting unmaintainable.
This PR cleans up all this, and makes the API crystal clear, by introducing the `v3` namespace:
v3 is a simple object representing our GitHub Rest API v3 client :
- `v3.call()` is the only function that calls GitHub. It receives the `url` and `parameters` arguments for the `fetch()` call and …
> refactor(api): Api clean up

- src/auth/screens/language-settings.js
- src/auth/screens/user-options.screen.js
Just a small addition to the great job from @lex111 
- Add the correct flag of **pt-br** language, in this case the Brazilian flag.
- Add emojiCode directly to language settings.
> refactor(languages): change pt-br flag and add emojiCode to languages

- src/components/loading-indicators/loading-container.component.js
I do not know why the height of the activity indicator is specified, but because of this, the entire block is not quite aligned correctly in the center. Therefore, instead I propose to indent text from the indicator through padding property.
> fix(loading-container): make correct center align

- App.js
- src/auth/auth.reducer.js
- src/auth/screens/auth-profile.screen.js
- src/user/screens/profile.screen.js
- src/user/user.reducer.js
This avoids the problem shown below: i.e. the number of stars has not yet loaded, and the number of repositories has already appeared, but you need to wait until all the data is loaded and only then show them all.
Before | After
| - | -
| <img src="https://user-images.githubusercontent.com/4408379/30869856-e7efeb2a-a2ea-11e7-8edd-6e5c1fa0bf04.gif" width="300" /> | <img src="https://user-images.githubusercontent.com/4408379/30869858-e9495c86-a2ea-11e7-90cc-3887a10c7718.gif" width="300" />
> refactor(profile): show user data when it is fully loaded

- src/components/user-profile.component.js
- src/locale/languages/en.js
- src/locale/languages/fr.js
- src/locale/languages/nl.js
- src/locale/languages/pt-br.js
- src/locale/languages/ru.js
- src/locale/languages/tr.js
The fact is that for the Russian language Following as an action means another word, so you need an extension of the localization (`followingYou`). 
And earlier we had in the blocks of the count of followers and following did not take into account the declension, so I added it. Although you may notice duplication in other languages, but now it is more flexible to translate.
Also within PR, the message has been moved to a single namespace, for greater clarity.
> refactor(profile): rename and extend messages for following and followers

- src/components/markdown-htmlview.component.js
Fix #363 
The problems were : 
- Text inside `<th>` was HTML escaped: it needed to be displayed using `defaultRenderer`
- An `<img>` inside a `<td>` caused a crash (View in Text): We created our own Cell component that avoids using `<Text>`
- marked() was rendering a simple `piece of code` as a `<pre>` if inside a `<li>`: Setting it to be pedantic helped
I also made images inside cells take 30% of the screen width while enlarging a bit images outside cells.
> fix(markdown): fix various markdown issues

- src/auth/screens/user-options.screen.js
At the moment the language element has different height: when inactive and active, it can be seen in the screenshot, this PR makes the same height for any state.
| Before | After
| - | -
| <img src="https://user-images.githubusercontent.com/4408379/30930108-475dd4f8-a3c9-11e7-9ef3-304ca0025b9b.png" width="300" /> | <img src="https://user-images.githubusercontent.com/4408379/30930117-4a9fc022-a3c9-11e7-91ec-c4e3347e2442.png" width="300" />
> fix(user-options): make height language item equal

- package.json
- yarn.lock
Yesterday I noticed that the dependence `react-native-photo-view` version 1.5.1 weighs about 80 MB! You probably can be waited a long time for doing `yarn` command, I waited a few minutes, and so I asked myself: why so long, and the problem was that this package weighed heavily because of the build-folders. So I wrote to the author about it, and he released a new version 1.5.2 and it weighs 200 KB :tada:
> chore(deps): update react-native-photo-view to 1.5.2

- src/issue/issue.action.js
Noticed this error while using Reactotron: 
`GET https://api.github.com/://github.com/gitpoint/git-point/pull/378.diff`
The problem was that `fetchDiff()` was called with `diff_url` from this struct:
which is outside the API, causing an error in `v3.call` while checking the presence of the API root.
Fixed by using `pull_request.url` that returns a diff when called with the `application/vnd.github.v3.diff+json` accept header
> fix(api): get diff from API instead of web

- src/auth/screens/events.screen.js
I have just noticed that after sign out the profile and when trying to log in, the events does not load, just a white screen, this PR fixes it.
> fix(events): get user events after login

- src/components/repository-list-item.component.js
- before:
- after:
Some hints:
- Original layout: starIcon-3-starCount-15-forkIcon-(-2)-forkCount-15-langIcon-3-langStr-15
- The 3 icons share the same width, which is 15, but:
- I don't know why forkIcon is left aligned, while the other 2 are center aligned
- Then,
- the space between forkIcon and forkCount is too narrow
- the space between starCount and langIcon is too wide
- So I adjust the layout to: starIcon-3-starCount-15-forkIcon-0-forkCount-13-langIcon-3-langStr-15
Please review or merge as you wish. I don't want this tiny PR bothers the v1.3 release.
> fix(ux): Fix a typo with tiny adjustment

- src/components/comment-list-item.component.js
Before this patch, the long press event in comment list item worked
in comments from other users, this action should work the logger
user comments.
Sorry for that mates! Was my bad 🙊
> fix(comments): fix long press click error

- src/repository/screens/repository-file.screen.js
Since the API change from #361, file source code fetching have not been working. 
The problem was calling `.download_url` which points to a raw file on `raw.githubcontents.com` instead of `.url` which holds a proper API url.
> fix(api): Run getRepositoryFile() through API, not raw.githubcontents

- src/api/index.js
Because if I have more than one thousand unread notifications, the badge will display `1.1k` for example, and it should be `99+`, because the number returned was not a number, but a string.
P.S. Made a return to default `false`, because in addition to fetching notifications count, `count` is used to fetch stars, and in general, it seems to me that this is an optional feature, and by default raw data should be returned.
> fix(notifications-count): return numbers without format

- src/components/github-htmlview.component.js
There was a nested View in Text when a `<img>` tag was used inside a `<li>` element (spotted on Antoine's comment in #381 )
Fixed by displaying the `alt` attribute of the image as a clickable text, opening the image with Linking for now:
> fix(md): Display a link instead of the image inside a <li>

- src/components/badge.component.js
- src/components/notification-icon.component.js
Update notifications icon badge:
1. Made it blue and text more prominent
2. Moved the `absolute` style logic to outside the badge component. If we plan on using this component elsewhere it shouldn't have absolute styling within
3. Extended props to include color and background color
CC @lex111
> style(notification-badge): Extend badge props + Refactor style

- src/auth/screens/events.screen.js
@housseindjirdeh [wrote](https://github.com/gitpoint/git-point/issues/381#issuecomment-333349250) that the screen of events is not updated after changing the language. This PR fixes this, I completely forgot about `extraData` from `FlatList`, which is  needed for similar purposes :confused:
> fix(events): update screen after change language

- src/locale/languages/pt-br.js
I just found one missing key 😄 
Asked in #411
> chore: Update pt-br translations

- src/api/index.js
- src/components/button.component.js
- src/components/comment-list-item.component.js
- src/components/issue-list-item.component.js
- src/components/repository-list-item.component.js
- src/issue/issue.action.js
- src/issue/issue.reducer.js
- src/issue/issue.type.js
- src/issue/screens/edit-issue-comment.screen.js
- src/notifications/screens/notifications.screen.js
- src/user/screens/repository-list.screen.js
- yarn.lock
Various fixes/updates for #381 
- Changes color of mark all notifications button
- Adds padding for no notifications message in notifications screen
- Fixes this problem:
- Allows editing of issue description
- Makes title/subtitle of `IssueDescriptionListItem` better in terms of boldness
- Removes the user title from repository list item (@lex111 - with this it's unlikely we'll see the `private` box being squeezed anymore as most repo titles aren't nearly as long)
> fix(*): Style updates, add edit issue body functionality

- src/api/index.js
- src/auth/screens/auth-profile.screen.js
- src/components/user-profile.component.js
- src/user/screens/profile.screen.js
This is a refactoring of refactoring :laughing:  Second attempt #366
In fact, in the past PR did not take into account the `auth profile`, and it was so that the block with the stars was displayed when there were none.
I need someone to check it, I need to know whether it's good now.
> refactor(profiles): show user data when it is fully loaded

- src/issue/screens/edit-issue-comment.screen.js
For #423 
`onContentSizeChange` doesn't seem to fire when the component mounts @jouderianjr so adding a height property seems to fix it
> fix(editissuecomment, textinput): Fix height rendering for Android

- src/notifications/screens/notifications.screen.js
The original replacement is not very safe, i.e,
```
'https://github.com/schacon/git-pulls/pulls/64'.replace('pulls', 'issues')
-> "https://github.com/schacon/git-issues/pulls/64"
'https://github.com/schacon/git-pulls/pulls/64'.replace(/pulls\/(\d+)$/, 'issues/$1')
-> "https://github.com/schacon/git-pulls/issues/64"
```
> fix(notification): Avoid repo names include keyword

- android/app/src/main/AndroidManifest.xml
This problem is only on Android, looked at the iOS-simulator, the tabbar is hidden there, but on Android no.
> fix(android): Hide tabbar when keyboard show

- CONTRIBUTING.md
- README.md
This branch:
- Removes a broken link to a project from the contributing doc.
- Notes what I think the "Authorization callback URL" should be, if you choose to create an OAuth app on GitHub to develop GitPoint locally.
> docs: add a couple of doc improvements

- src/components/github-htmlview.component.js
This fix should be a bit more solid:
- enhance `<img />` extraction from spans
- if it didn't work, and an `<img>` is in a `<span>` at render time, render it as a label
- check `<ul>`|`<ol>` for lists, instead of `<li>` cause I need to remove the `<li>` for tasks, which breaks the detecetion
Should fix  #437, #363 and #429
> fix(md): Image related fixes

- src/components/issue-description.component.js
- src/issue/issue.action.js
- src/issue/issue.reducer.js
- src/issue/issue.type.js
- src/issue/screens/issue.screen.js
Fixes #128.
The main idea is to leverage the field `mergeable` provided by [the pull request API](https://developer.github.com/v3/pulls/#get-a-single-pull-request). Besides, I refactor a little about the logic of fetching a issue. That's because I want to only fetch pull request if the issue is a pull request. At last, I find out some basic fields are still needed by using the issue API, so I give up the API replacement but keep the refactor.
> feat(issue): Disable merge button if not possible

- src/components/github-htmlview.component.js
Fix a new markdown bug, this time with anchors.
Also got rid of `node.children[0].data` in favor of `defaultRenderer(node.children, node)`, so that links containing more than a single text child are well rendered.
Like this one for example with the commit hash at the end: https://github.com/machour/git-point-playground/commit/4872692e48c9b18c8df9ec8acadbbfab2306d1c6
Fixes #462
> fix(md): Play nice with anchors

- routes.js
~~Fixes~~ Discovered in #462.
The regular expression can't match anything if `issueURL` is a issue comment, like `https://github.com/octokit/discussions/issues/7#issuecomment-327616339`. It causes `[1]` throws an error.
```
const issueNumberRegex = /issues\/([0-9]+)$/;
const { issue, issueURL, isPR, language } = navigation.state.params;
const number = issue ? issue.number : issueURL.match(issueNumberRegex)[1];
```
> fix(issue): Consolidate issue link parsing

- ios/GitPoint.xcodeproj/xcshareddata/xcschemes/GitPoint.xcscheme
When using xcode, logs are flooded with this message (X incrementing every 2 seconds):
`[] nw_connection_get_connected_socket_block_invoke X Connection has no connected handler`
setting OS_ACTIVITY_MODE = disable fixes it, and logs are bearable again
> chore: disable OS_ACTIVITY_MODE in Debug mode

- src/locale/languages/en.js
- src/locale/languages/es.js
- src/locale/languages/fr.js
- src/locale/languages/gl.js
- src/locale/languages/nl.js
- src/locale/languages/pt-br.js
- src/locale/languages/pt.js
- src/locale/languages/ru.js
- src/locale/languages/tr.js
- src/repository/screens/read-me.screen.js
Hey guys,
i found a string in `readme.screen.js`
I added it to the translation files but the translators need to translate it now.
Im not sure, probably @housseindjirdeh wanted this string to be not translate or it was just overseen somehow. If its wanted this way please close this pr.
Thank you guys
> fix(translation): add missing string to translations

- package.json
- src/auth/screens/events.screen.js
- src/auth/screens/user-options.screen.js
- src/components/comment-list-item.component.js
- src/components/issue-description.component.js
- src/issue/screens/edit-issue-comment.screen.js
- src/issue/screens/issue-settings.screen.js
- src/issue/screens/issue.screen.js
- src/issue/screens/new-issue.screen.js
- src/issue/screens/pull-merge.screen.js
- src/locale/languages/eo.js
- src/notifications/screens/notifications.screen.js
- src/organization/organization.reducer.js
- src/organization/screens/organization-profile.screen.js
- src/repository/screens/read-me.screen.js
- src/repository/screens/repository.screen.js
- src/user/screens/profile.screen.js
- src/user/screens/repository-list.screen.js
Under normal conditions, prettier is only run on the lines of code that are changes in that commit. This cleans up all the code that doesn't currently conform to our prettier configuration, making the style completely consistent across all files again (and fixes the failing CI).
The command to run this cleanup yourself:
```bash
$ prettier --single-quote --trailing-comma es5 --write "**/*.js"
$ # or
$ yarn prettier
```
> refactor(*): cleanup code using prettier

- ios/GitPoint.xcodeproj/project.pbxproj
- ios/GitPoint/Info.plist
Related to #402.
Picked out necessary fonts(FontAwesome, MaterialIcons and Octicons), according to 
[react-native-vector-icons docs](https://github.com/oblador/react-native-vector-icons#option-manually).
@machour I only have iOS development environment, hope you can tweak app.gradle as well.
> feat(fonts): Remove useless fonts in iOS

- App.js
- CONTRIBUTING.md
- package.json
- yarn.lock
Adding `styled-components` initial work! 🙌
> feat(styling): add styled components

- package.json
- src/components/github-htmlview.component.js
- src/components/index.js
- src/components/toggle-view.component.js
- yarn.lock
Introduced a `<ToggleView>` component which will also come handy when we add PR review comments.
Closes #467
> feat(markdown): Add support for quoted emails

- package.json
- src/auth/screens/login.screen.js
- yarn.lock
We weren't using any of the advanced features of react-native-app-intro.
This should fix the compatibility issue for #406
> refactor: Drop rn-app-intro in favor of react-native-swiper

- src/auth/screens/auth-profile.screen.js
Hey everyone, one friend has reported that if we navigate to an AuthProfile in the middle of some StackNavigator will be locked on the screen because the back button doesn't appear, so this pull request fixes it.
> fix(ux): Add back button for AuthProfileScreen

- src/components/comment-list-item.component.js
- src/components/inline-label.component.js
Slight styling adjustments:
- Made issue event badges slightly smaller
- Changed username press from TouchableOpacity to Text onPress
CC @brandly
> fix: slight issue event badge + comment click styling

- src/components/parallax-scroll.component.js
`window` was used without ever being defined & setting `width` is not needed (tested on iOS & Android while changing device orientation)
This only causes an error with RN 0.49.3, really curious Oo.
> fix: Remove undefined var & fix typo

- ios/GitPoint.xcodeproj/project.pbxproj
- ios/GitPoint/Info.plist
- rn-cli.config.js
With `rn-cli.config.js`, we can ignore assets that `react-native-vector-icons` defines in [its rnpm config](https://github.com/oblador/react-native-vector-icons/blob/master/package.json#L57). So that `react-native link` will not link those assets into our project again.
I removed some useless fonts for iOS in #475, but @housseindjirdeh and @machour pointed that `yarn run link`(which runs `react-native link` in fact) will add them back. It is really hard to find a thorough document about `react-native link`. Fortunately, I find the way to solve this problem after dig into RN source codes[[1](https://github.com/facebook/react-native/blob/master/local-cli/link/link.js#L198), [2](https://github.com/facebook/react-native/blob/master/local-cli/link/getDependencyConfig.js#L9)].
By the way, I …
> chore: fix `yarn run link`

- src/auth/screens/login.screen.js
Seems like this is now needed by `react-native-elements` button to correctly render a transparent button absolutely positioned.
(we bumped from "^0.9.3" to "^0.17.0" in #407)
> fix: Fix button transparency on Android

- src/components/image-zoom.component.js
Hey, Jouderian here doing another small PR 😄 
I've noticed that back button in ImageZoom component was doing nothing, but in Android is quite common uses back button action to close a modal.
> fix(ux): Add Back button event on ImageZoom component

- __tests__/tests/components/RepositoryProfile.js
- src/components/repository-profile.component.js
- testenv.js
- Add tests for Repository Profile Component
- Mock ‘react-native-safari-view’
Related to #518
> test: Add RepositoryProfile tests

- yarn.lock
Updates hash for react-native-mock to match expected `96bee7b072cea66f5dfa21c39b2416ca6fb6c0da`.  
This also causes some cascading changes in the lock file after running `yarn` (install) again so should be treated with caution.   
Tested on Android (physical) and iOS simulator.
> Fix: Updated yarn.lock hash for react-native-mock

- src/components/section-list.component.js
This problem is only happening on Android.
> fix: fix section list button height

- src/issue/screens/issue.screen.js
Before #438, data of `FlatList` only contained issue and comments. But now events are included, which have no field calls `id`. (I changed 2 lines and prettier did the rest. 😱 )
```
const conversation = !isPendingComments
? [issue, ...comments, ...events].sort(compareCreatedAt)
: [];
```
> fix(warning): Fix the key extractor of issue screen

- .gitignore
I've seen a couple of PRs that include `package-lock.json` file. Because we're using yarn this file won't be necessary.
> chore(*): Remove package-lock.json

- .travis.yml
`yarn` is run by default in the install step.
> chore: remove unneeded install step

- src/components/issue-event-list-item.component.js
Migrate StyleSheet styles to StyledComponents form
#532
> refactor(styles): Refactor IssueEventListItem component

- src/components/image-zoom.component.js
> refactor: use styled-components in image-zoom

- .babelrc
- .eslintrc
- __tests__/data/api/error.js
- __tests__/data/api/search.js
- __tests__/tests/reducers/search.reducer.js
- src/search/search.reducer.js
Nice easy one to add tests for the search reducer.   
Includes changes to add aliases to `.babelrc` and `.eslintrc` from #567 in order to past tests as PR's may not be merged in order and obviously not being able to open PR against master here or the branch from #567 since it exists in the fork not upstream.
> test: added search reducer tests

- __tests__/tests/utilities/color-helpers.js
Hello,
I've added tests for the color helper :)
> test: Add test for Color Helpers (#518)

- __tests__/tests/utilities/text-helper.js
> test(text-helper): add test for emojifyText, abbreviateNumber

- src/issue/issue.reducer.js
If you try to visit an opened issue after a merged PR, there will be no `Close Issue` button in issue settings screen. [Related codes](https://github.com/gitpoint/git-point/blob/master/src/issue/screens/issue-settings.screen.js#L266).
The reason is that pull request related fields in the store are not reset. I have to admit that resetting these field in the handle of `GET_ISSUE_FROM_URL.SUCCESS` is a little wired. But before we have refactored our redux store, it is hard to find a more elegant way.
> fix(issue): Fix pull request related fields are not reset

- src/components/issue-description.component.js
Migrating StyleSheet styles to styled components
Related #532
> refactor(styles): IssueDescription component styles update

- __tests__/tests/components/Button.js
- __tests__/tests/components/ToggleView.js
- package.json
- yarn.lock
Per #588, removes the dependency on sinon and uses jest builtin mocks.
> refactor(tests): use jest mocks instead of sinon spies

- __tests__/tests/others/locales.js
> test(locales): Add locales test

- src/components/comment-input.component.js
> refactor: comment input to styled components

- src/components/code-line.component.js
- src/components/entity-info.component.js
- src/components/image-zoom.component.js
- src/components/inline-label.component.js
- src/components/issue-description.component.js
- src/components/issue-event-list-item.component.js
- src/components/mention-area.component.js
~~WIP.~~
Modified by stylelint's suggestions. Including:
- add missing commas
- fix unexpected token
- fix unsupported properties, like `padding-horizonal`
- fix unitless shorthands properties
- replace multi properties by shorthands
The last thing is that, is there a better way for empty tagged template? `stylelint` will throw a warning. Of course, maybe we can add a rule to ignore it.
```
const StyledListItem = styled(ListItem).attrs({
...
hideChevron: props => props.unknown,
})``;
```
> fix(sc): Fix by stylelint

- src/components/code-line.component.js
SyntaxHighlighter is not stylable as it uses the `style` props for something totally different.
Fixes #616
> fix(crash): Fix crash in PullDiff screen

- package.json
- src/components/entity-info.component.js
- src/components/issue-description.component.js
- src/components/issue-event-list-item.component.js
- src/components/repository-list-item.component.js
- src/repository/screens/repository-code-list.screen.js
- src/repository/screens/repository.screen.js
- yarn.lock
Spent the afternoon fixing up the problems introduced by the styled-components migration:
- Upgrade to react-native-elements 0.18.1 which contains a fix for styled components supports
- Fixed problems:
1. `<EntityInfo/>`: The test on the company was inverted. Also renamed the prop.
2. `<IssueDescription/>`: Fix the repo link header, the issue title & use InlineLabel instead of LabelButton for issues/pulls label
3. `<IssueEventListItem/>`: Fix icon styling
4. `<*List />` : Adjusted the border bottom color, as the default changed in RNE from 0.7 to 0.17 and this is why we had bolder lines.
This should fix #615 #580 and several comments in #569
> fix(styled-components): Fix react-native-elements related problems

- __tests__/tests/components/NotificationListItem.js
- src/components/notification-list-item.component.js
|![simulator screen shot - iphone 6 - 2017-10-30 at 12 26 57](https://user-images.githubusercontent.com/2670744/32176964-2b7e524c-bd70-11e7-9989-ee05a71b8452.png)|![simulator screen shot - iphone 6 - 2017-10-30 at 12 32 50](https://user-images.githubusercontent.com/2670744/32177006-42f40624-bd70-11e7-81b2-e88fc8432dd9.png)|
Migrate NotificationListItem component to styled-components (#532)
> refactor: NotificationListItem to used styled-components

- src/components/notification-list-item.component.js
> refactor: use an enum for subject types

- .travis.yml
Should fix #632.
Due to https://github.com/travis-ci/travis-ci/issues/1066, the solution is not as simple as inverting the two lines.
Instead, I made the script a one liner that runs eslint before coverage.
This is not tested as I don't want to create a fake & bogus PR :/
> chore: Make travis run eslint first and fail immediately if needed

- android/app/build.gradle
| Devices tested?  | Android Nexus 5X (simulator) |
| Related ticket?  | #630        |
---
| ![screen shot 2017-11-06 at 9 40 08 am](https://user-images.githubusercontent.com/304450/32433457-4d63c61a-c2db-11e7-9c43-19afaef3cb27.png) | ![screen shot 2017-11-06 at 10 14 16 am](https://user-images.githubusercontent.com/304450/32433464-5510d222-c2db-11e7-90d0-790fb17a21d8.png) | 
Added Ionicons.ttf compilation back in `build.gradle` as it is needed by `react-native-material-design-searchbar`.
/cc @dyesseyumba for info …
> fix(search-bar): Compile Ionicons for Android

- src/components/comment-input.component.js
Noticed a few things that could be enhanced while working on #622.
Tested on both iOS and Android, no regressions introduced:
>  refactor(comment-input): Clean up code & styled-components

- .stylelintrc
- .travis.yml
- package.json
- yarn.lock
As discussed in #604, I integrated `stylelint` by following styled-components [tutorial](https://www.styled-components.com/docs/tooling#stylelint).
Please notice that even with the official `stylelint-processor-styled-components`, `stylelint` is not 100% compatible with styled-components. So I added some customized rules.
```
"rules": {
// 1
"block-no-empty": null,
// Inspired by https://github.com/styled-components/css-to-react-native/blob/master/src/tokenTypes.js#L31
// to avoid unitless shorthands properties crash
"declaration-property-value-whitelist": {
"margin": ["/^(0|[+-]?(\\d*\\.)?\\d+px)( (0|[+-]?(\\d*\\.)?\\d+px))?$/"],
"padding": ["/^(0|[+-]?(\\d*\\.)?\\d+px)( (0|[+-]?(\\d*\\.)?\\d+px))?$/"],
},
// 2
"declaration-colon-newline-after": null,
"value-list-max-empty-lines": null …
```
> chore(lint): Add stylelint script

- App.js
---
This PR silences the following warning on iOS by testing the platform OS:
```
2017-12-04 14:05:11.418 [warn][tid:com.facebook.react.JavaScript] `setTranslucent` is only available on Android
2017-12-04 14:05:11.418 [warn][tid:com.facebook.react.JavaScript] `setBackgroundColor` is only available on Android
```
> fix: setTranslucent and setBackgroundColor are Android only

- src/components/badge.component.js
| Devices tested?  | iPhone 7, Android Nexus 5 |
| Related ticket?  | #581        |
---
| <img width="349" alt="screen shot 2017-11-25 at 2 41 37 pm" src="https://user-images.githubusercontent.com/304450/33231134-6c33bb08-d1f0-11e7-939b-b3036f974dbd.png"><img width="343" alt="screen shot 2017-11-25 at 2 46 08 pm" src="https://user-images.githubusercontent.com/304450/33231135-6c4eeebe-d1f0-11e7-8fd2-ee4d5adb805c.png"> | <img width="350" alt="screen shot 2017-11-25 at 2 48 19 pm" …
> fix: re-enable color prop for the badge component

- src/components/github-htmlview.component.js
---
While working on #609 with @ArvinH, we discovered a potential crash in the `<code>` element rendering while checking for its parent tag.
This PR fixes the crash by testing for parent existence.
> fix(crash): Fix potential crash on undefined parent in <code>

- src/issue/screens/issue.screen.js
| Devices tested?  | iPhone 6 simulator, iOS 11.0 |
| Related ticket?  | #655        |
---
Fixes #655.
This bug was introduced by #438. `getIssueEvents` should not be invoked until `this.props.issue/repository` were updated.
In fact, besides the crash problem, the unfixed codes may also get wrong issue events due to `getRepository` was not returned.
> fix(issue): Fix wrong repository was used

- src/issue/screens/issue.screen.js
| Devices tested?  | iPhone 6, iOS 11.0 simulator |
| Related ticket?  | #201        |
---
From #332, we can learn that `this.props.navigation.state.params.issue` is not available when visiting from notifications. The safer variable is `this.props.issue`.
By scanning similar codes, I found another crash and fixed. If visiting an issue without push permissions, you can invoke an action sheet from the top right corner and select `Open in Browser`, then the app will also crash.
> fix(issue): Fix crash due to undefined navigation params

- src/components/button.component.js
| Devices tested?  | iPhone 7, Nexus 5 |
| Related ticket?  | #624         |
---
| <img width="315" alt="screen shot 2017-12-09 at 12 02 18 pm" src="https://user-images.githubusercontent.com/304450/33795053-ffd243be-dcd8-11e7-8a16-190d5ac9ce1a.png"> | <img width="314" alt="screen shot 2017-12-09 at 11 59 42 am" src="https://user-images.githubusercontent.com/304450/33795055-0a0872a4-dcd9-11e7-8324-6b10d3879b4f.png"> |
This PR fixes the second and last problem mentionned in #624. `react-native-elements` introduced a …
> fix(android): fix Button layout

- src/components/issue-description.component.js
| Question .           | Response    |
| ---------------- | ------------ |
| Version?             | master .        |
| Devices tested? | iPhone 7, Nexus 5 |
| Bug fix?              | yes               |
| New feature?     | no                 |
| Includes tests?  | no                 |
| All Tests pass?  | yes               |
| Related ticket?  | #624            |
---
| <img width="348" alt="screen shot 2017-12-09 at 11 27 57 am" src="https://user-images.githubusercontent.com/304450/33794838-1c560c64-dcd4-11e7-8f73-09e5615f64e3.png"> | <img width="347" alt="screen shot 2017-12-09 at 11 26 35 am" src="https://user-images.githubusercontent.com/304450/33794839-210e8fec-dcd4-11e7-8ad9-bc24dc0abfed.png"> |
Removed two (unneeded) styles from the …
> fix: remove containers styles that confuses the button

- App.js
| Devices tested?  | iPhone 7, Android Nexus 5 |
| Related ticket?  | none        |
---
This PR removes everything but `auth` from the persistent storage.
Motivation is that there's no point in keeping this information, and it's sometime a pain in the A.
Example:
* Go to an issue that crashes because of some markdown problem
* Restart the app
* Go to another issue that shouldn't crash.
* App crashes because it's still parsing the old markdown from store, before getting the new one
This was partially discussed here: …
> feat(store): blacklist everything but auth from persistent storage

- src/notifications/screens/notifications.screen.js
|![before-none](https://user-images.githubusercontent.com/5565340/34450557-090b0c32-ed04-11e7-85b9-abe50e6ba898.png)| ![after-none](https://user-images.githubusercontent.com/5565340/34450558-092513fc-ed04-11e7-961b-76dd2d032e71.png)|
|![before-notifications](https://user-images.githubusercontent.com/5565340/34450556-0490615c-ed04-11e7-800c-75c3e69f70d8.png)|![after-notifications](https://user-images.githubusercontent.com/5565340/34450555-0477fc8e-ed04-11e7-9e9d-3a162956d53c.png)|
Part of #532.
> refactor: migrate notifications screen to styled-components

- src/user/screens/repository-list.screen.js
|![before-repos](https://user-images.githubusercontent.com/5565340/34450516-fd154614-ed02-11e7-8be5-2f746c2a67ee.png)|![after-repos](https://user-images.githubusercontent.com/5565340/34450517-ff422434-ed02-11e7-9847-945e57eaea07.png)|
Part of #532.
> refactor: migrate user repo list screen to styled-components

- src/organization/screens/organization-profile.screen.js
|![before](https://user-images.githubusercontent.com/5565340/34411018-f7d65b76-ebcb-11e7-9608-bcacfa4b7109.png)|![after](https://user-images.githubusercontent.com/5565340/34411017-f68f0a9c-ebcb-11e7-9176-9efce2cad565.png)|
Part of #532.
> refactor: migrate organization screen to styled-components

- src/auth/screens/login.screen.js
| Devices tested?  | Android Nexus 5 (simulator) |
| Related ticket?  | #680        |
---
Enabled javascript in the WebView for Android, which is needed on the authorization screen. 🙈
> fix(login): enable javascript in the webview for Android

- __tests__/tests/components/ImageZoom.js
- src/components/image-zoom.component.js
So, this is my test proposal for ImageZoom 😄 
I'm accepting any type of suggestions 💃
> test: Add test to ImageZoom component

- .travis.yml
> yarn run v1.3.2
warning You are using Node "7.10.1" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
The CI warns that `yarn` is not compatible with Node.js 7. We also complained that the CI is too slow. Let me try to upgrade Node.js version and compare the time.
> chore(ci): Upgrade CI Node.js version to 8

- src/auth/screens/events.screen.js
|![events-before](https://user-images.githubusercontent.com/5565340/34639610-f50d4344-f2da-11e7-88bc-37329111d7b8.png)|![events-after](https://user-images.githubusercontent.com/5565340/34639611-f5259106-f2da-11e7-8a68-c62428475969.png)|
I also noticed the branch name (see first event) wasn't getting the LinkBranchDescription code style as it does in 'create events' despite the fact GH also has that styling for 'push events'. So I added that.
(Part of #532)
> refactor: migrate events screen to styled-components

- src/components/diff-blocks.component.js
---
|![screen shot 2018-01-14 at 12 09 13 pm](https://user-images.githubusercontent.com/304450/34915307-595146b2-f924-11e7-9efa-c4da2626a6bf.png)|![screen shot 2018-01-14 at 12 05 18 pm](https://user-images.githubusercontent.com/304450/34915304-4c94babc-f924-11e7-8e34-fc3f015173e6.png)|
|![screen shot 2018-01-14 at 12 09 24 pm](https://user-images.githubusercontent.com/304450/34915309-64d6f464-f924-11e7-8e18-17c441c84ea9.png)|![screen shot 2018-01-14 …
> refactor(diff-blocks): switch to styled components

- src/components/badge.component.js
- src/components/code-line.component.js
- src/components/inline-label.component.js
- src/components/issue-event-list-item.component.js
- src/components/notification-list-item.component.js
- src/config/index.js
- src/config/styled-fonts.js
- src/notifications/screens/notifications.screen.js
| Related ticket?  | #688    |
---
|![simulator screen shot - iphone 6 - 2018-01-14 at 13 41 35](https://user-images.githubusercontent.com/304450/34916010-e1a07ca2-f930-11e7-96a7-12a5f96c860b.png)|![simulator screen shot - iphone 6 - 2018-01-14 at 13 22 20](https://user-images.githubusercontent.com/304450/34915935-734f9f18-f92f-11e7-9fa3-9af1d755502a.png)|
|![simulator screen shot - iphone 6 - 2018-01-14 at 13 42 57](https://user-images.githubusercontent.com/304450/34916014-f6603678-f93 …
> refactor(sc): remove styledFonts in favor of fonts

- src/user/screens/repository-list.screen.js
| Version?         | dev-master     |
| Related ticket?  | #694        |
---
|![simulator screen shot - iphone 6 - 2018-01-15 at 23 15 32](https://user-images.githubusercontent.com/304450/34964115-41d23eaa-fa4c-11e7-91c5-9902c8e07145.png)|![simulator screen shot - iphone 6 - 2018-01-15 at 23 30 44](https://user-images.githubusercontent.com/304450/34964114-41b08a4e-fa4c-11e7-9624-903906d0f042.png)|
Reintroduced the `<View>` element removed in #683
> fix: reintroduce View to avoid list being cropped

- src/auth/screens/auth-profile.screen.js
- src/auth/screens/privacy-policy.screen.js
- src/auth/screens/splash.screen.js
- src/auth/screens/user-options.screen.js
- src/auth/screens/welcome.screen.js
|![screen shot 2018-01-20 at 18 55 24](https://user-images.githubusercontent.com/5565340/35186920-1b65664a-fe14-11e7-9ce3-5b64564b08b2.png)|![screen shot 2018-01-20 at 18 40 34](https://user-images.githubusercontent.com/5565340/35186921-1dc1b97a-fe14-11e7-8373-1649a3fa2165.png)|
|![screen shot 2018-01-20 at 18 56 09](https://user-images.githubusercontent.com/5565340/35186928-25d397d2-fe14-11e7-8194-d49f4db41815.png)|![screen shot 2018-01-20 at 18 29 11](https://user-images.githubusercontent.com/5565340/35186929-29932d1a-fe14-11e7-8453-fc9457ccb32f.png)|
|![screen shot 2018-01-20 at 18 44 36](https://user-images.githubusercontent.com/5565340/35186934-379d0a84-fe14-11e7-9ebb-edd5d7df7590.png)|![screen shot 2018-01-20 at 18 35 …
> refactor(auth): migrate auth screens to styled-components

- src/issue/screens/issue.screen.js
| Related ticket?  | #660        |
---
This is an attempt to fix the scrolling problem reported in #660. After posting the comment, the comment list didn't really scroll all the way down.
This was due to two reasons:
1. `scrollToBottom()` was fired before the api call returned the new comment
2. There is a bug in `FlatList` that fails to really scroll to bottom when using `ListComponentHeader` without implementing `getItemLayout` (that would allow to RN to compute the list height).
This PR solves 1 by scrolling when the API …
> fix: scroll to real list bottom after posting a comment

- __tests__/tests/others/locales.js
- package.json
- yarn.lock
I was looking at the travis-ci build output for a failure on #638 to try to figure out the problem, and I found it to be really unhelpful as it generates **~600** lines of diff like this when there's a key mismatch
full log [here](https://travis-ci.org/gitpoint/git-point/builds/336108646). It's almost impossible to tell which keys are missing.
changed the test to use `keys-diff` for a minimalistic straight-forward output:
> test: make locale test output more readable

- .stylelintrc
- src/components/comment-list-item.component.js
---
|![3 pic](https://user-images.githubusercontent.com/1736154/36089659-071d08d0-1018-11e8-9baa-7aad1ee9d2b7.jpg)|![2 pic](https://user-images.githubusercontent.com/1736154/36089665-0d2d3092-1018-11e8-80c8-c02050f16868.jpg)|
Based on #557. Thank @MrLoh all the same.
> refactor: use styled-components in comment-list-item

- src/components/github-htmlview.component.js
| Devices tested?  | iPhone 7... |
| Related ticket?  | #728         |
---
| ![simulator screen shot - iphone 6 - 2018-02-14 at 10 55 53](https://user-images.githubusercontent.com/304450/36198571-36f6c7b6-1177-11e8-8dd0-96c8d893233c.png) |  ![simulator screen shot - iphone 6 - 2018-02-14 at 11 00 26](https://user-images.githubusercontent.com/304450/36198575-3e82f6f8-1177-11e8-9b92-4f90d34d9569.png) |
Instead of testing that the content of the text chunk if "\n" to replace it with our own vertical spacer, I now make …
> fix: remove extra spaces from empty text nodes

- __tests__/tests/components/StateBadge.js
- src/components/issue-description.component.js
- src/components/state-badge.component.js
| Devices tested  | iPhone 6 |
---
|![before](https://user-images.githubusercontent.com/5786033/35767750-4271f7ce-08f2-11e8-82f3-23aa0f9f9e59.png)|![after](https://user-images.githubusercontent.com/5786033/35767757-5d8594ee-08f2-11e8-82de-fab00dc74c84.png)|
|![before](https://user-images.githubusercontent.com/5786033/35767776-8c5e4bc6-08f2-11e8-82a6-836b3ad6959f.png)|![after](https://user-images.githubusercontent.com/5786033/35767771-7de6eb3e-08f2-11e8-84a8-7f13a69e7291.png)|
This PR is related with the update of the StateBadge component. Now it uses styled-components as a driver to style the user …
> Refactor StateBadge component

- src/components/index.js
- src/components/user-profile.component.js
---
|![5 pic](https://user-images.githubusercontent.com/1736154/36142863-4378ee1c-10e4-11e8-81b9-5cb6e48d8f84.jpg)|![4 pic](https://user-images.githubusercontent.com/1736154/36143039-e4c22bbc-10e4-11e8-86ce-3e08f988d580.jpg)|
Repick #577 and update badge styles the same with #709.
> refactor(user-profile): use styled-components

- src/components/inline-label.component.js
- src/components/label-button.component.js
- src/issue/screens/issue-settings.screen.js
| Bug fix?         | yes/no      |
| Related ticket?  | #734   |
---
| ![before](https://user-images.githubusercontent.com/3621147/36637499-a9bdf3dc-1a28-11e8-8a60-8bb2ea47c026.png)|![after](https://user-images.githubusercontent.com/3621147/36637418-f9a00dd8-1a26-11e8-858a-7da9c919dd14.png) |
| ![before](https://user-images.githubusercontent.com/3621147/36637497-a101ded4-1a28-11e8-805c-b800969c3982.png)|![after](https://user-images.githubusercontent.com/3621147/36637425-375e4c02-1a27-11e8-98dc-6e5b6c613109.png) |
| …
> feat: Emoji support for Labels

- src/search/screens/search.screen.js
prevent sending request for same query while switching between repo and user search
| Devices tested?  | one plus5 |
| Related ticket?  |         |
---
Switching between search results of user and repo makes a new request every time even for the same query for which the result is already available. Added logic to prevent this.
> refactor(search): refactor search switch between user and repo

- src/auth/screens/login.screen.js
- src/locale/languages/de.js
- src/locale/languages/en.js
- src/locale/languages/eo.js
- src/locale/languages/es.js
- src/locale/languages/eu.js
- src/locale/languages/fr.js
- src/locale/languages/gl.js
- src/locale/languages/nl.js
- src/locale/languages/pl.js
- src/locale/languages/pt-br.js
- src/locale/languages/pt.js
- src/locale/languages/ru.js
- src/locale/languages/tr.js
- src/locale/languages/uk.js
- src/locale/languages/zh-cn.js
- src/locale/languages/zh-tw.js
| Devices tested?  | OnePlus 5t |
| Related ticket?  | #732 #674 #680    |
---
| ![screenshot_20180324-125009](https://user-images.githubusercontent.com/304450/37863793-6ea05b86-2f64-11e8-92c6-2a4c79fc4282.jpg) | ![screenshot_20180324-124806](https://user-images.githubusercontent.com/304450/37863795-738620f4-2f64-11e8-970d-4e9a54e786de.jpg) |
Some users complained about the "Login" button being disabled in the WebView. 
This is because GitHub disables it from some old/stock android browsers.
This PR simply adds a …
> fix(login): Provide an escape hatch for Android

- src/api/actions/index.js
- src/api/client.js
- src/api/reducers/pagination.js
- src/api/schemas/index.js
- src/api/schemas/repos.js
- src/user/screens/starred-repository-list.screen.js
- src/user/user.action.js
- src/user/user.reducer.js
- src/user/user.type.js
---
In order to further explain the new API, this PR demonstrate how we turn a limited list of repositories (50), into a paged list displaying all repositories. I did that on the starred repositories list displayed on a user profile.
By chance, the file changes are well ordered, so I'll break down the migration steps in comments.
Once merged, we will have two screens using the new pagination API (events & starred repos), so next PR will be about a little refactoring:
- Adding a new `<PaginatedFlatList />` component and using it in …
>  feat: Make the starred repositories list paged

- .gitignore
- ios/GitPoint.xcodeproj/project.pbxproj
This one have been making me crazy since day 1: I never was able to run the app on ios simulator without hardcoding my IP in `AppDelegate.m` like this:
```diff
- jsCodeLocation = [[RCTBundleURLProvider jsBundleURLForBundleRoot:@ sharedSettings] "index.ios" fallbackResource:nil];
+ jsCodeLocation = [NSURL URLWithString:@"http://192.168.1.183:8081/index.ios.bundle"];
```
I discovered today that you can provide a file named `ip.txt` in Xcode and put the IP there instead:
https://github.com/facebook/react-native/blob/master/React/Base/RCTBundleURLProvider.m#L86
This PR add this empty file to Xcode and to gitignore at the same time, so you are free to put any IP there if needed.
I still need someone with a working setup without hardening the IP to give this a go.
<i>(And `git status` will …
> chore: add and ignore ip.txt in ios

- package.json
- src/api/proxies/create-dispatch-proxy.js
- yarn.lock
@MrZhang123 reported on gitter that he wasn't able to run the project anymore on Genymotion, due to the lack of ES6 Proxies in this environment.
This PR adds a polyfill. Tested and validated on a Genymotion 6.0.0 (api 23) player.
I've did a lot of googling about whether or not RN supports proxies in all targets for the Release build, and after reading a bunch of stuff, all I'm certain of is that I'm really uncertain. I would be really thankful if anyone could provide a clear explanation about this. 🙏
> fix: add a Proxy polyfill to make sure it's available everywhere

- android/app/build.gradle
- android/app/src/main/java/com/gitpoint/MainApplication.java
- android/settings.gradle
- ios/GitPoint.xcodeproj/project.pbxproj
- package.json
- src/components/image-zoom.component.js
- yarn.lock
| Devices tested?  | iPhone 7, OnePlus 5t |
| Related ticket?  | #584     |
---
Added support for remote SVG images in the ImageZoom component.
The idea is to still use the `<Image>` component from React Native, and `onError`, let `react-native-svg-from-uri` take a chance at rendering.
(I forked `react-native-svg-from-uri` from `react-native-svg-uri` which is not maintained anymore, and fixed some text rendering issues that made me walk away when I first tried this lib a while ago.)
SVG are not zoomable for now, as react-native-photo-view doesn't support SVG. No …
> feat: add support for SVG images in ImageZoom component

- src/auth/screens/events.screen.js
- src/components/loading-indicators/index.js
- src/components/loading-indicators/loading-event-list-item.component.js
- src/utils/loading-animation.js
| Devices tested?  | iPhone 7, OnePlus5T |
| Related ticket?  | none        |
---
| ![simulator screen shot - iphone 6 - 2018-04-02 at 13 05 11](https://user-images.githubusercontent.com/304450/38195665-82856a60-3676-11e8-951e-97019c1cbd1c.png)|![simulator screen shot - iphone 6 - 2018-04-02 at 12 57 10](https://user-images.githubusercontent.com/304450/38195674-8fba4d04-3676-11e8-9b4b-a19908a52fff.png)|
Created a new `<LoadingEventListItem />` component used as a placeholder in the events screen.
Prior to the Redux …
> feat: Add LoadingEventListItem

- src/api/client.js
- src/api/proxies/create-dispatch-proxy.js
- src/api/reducers/pagination.js
- src/utils/action-helper.js
- src/utils/api-helpers.js
As mentioned in #770, this is the smallest subset of changes required for the Proxy<=>Client refactoring.
* Client methods don't trigger the `fetch()` anymore, but instead hands out all call parameters to the Proxy
* only `list` and `get` operations are supported
* Got rid of the weird & confusing `splitArgs()` things.
* Our actions sets now contain the action "name"
Tested all the screens migrated to the new API so far, every one of them still work without changing a single char.
> refactor: rewrite proxy <=> client internals

- __tests__/tests/components/RepositoryProfile.js
- src/api/actions/index.js
- src/api/client.js
- src/api/index.js
- src/api/proxies/create-dispatch-proxy.js
- src/api/queries/index.js
- src/api/queries/repo.query.js
- src/api/reducers/entities.js
- src/api/reducers/pagination.js
- src/api/schemas/gql-repos.js
- src/api/schemas/index.js
- src/components/issue-list-item.component.js
- src/components/repository-profile.component.js
- src/repository/repository.action.js
- src/repository/repository.reducer.js
- src/repository/repository.type.js
- src/repository/screens/repository-code-list.screen.js
- src/repository/screens/repository.screen.js
- src/utils/index.js
- src/utils/migration-helper.js
| All Tests pass?  | no      |
| Related ticket?  | #761         |
---
Introducing GraphQL in the new Redux API 🎉 
Rewrote the repo screen to be loaded with only two requests:
* A GraphQL query to load all the displayed information on the screen
* A REST list query to load the contributors (not provided by GitHub v4 yet)
I also ported star/unstar watch/unwatch & fork to the new API.
For now, the GraphQL query also returns 50 issues & 50 pull requests, to avoid making any changes to the issues/pulls list screens. We will get rid of that once these two screens are …
> refactor(repository-screen): switch to GraphQL

- src/components/loading-indicators/loading-container.component.js
---
|![simulator screen shot - iphone 6s - 2018-04-23 at 18 43 58](https://user-images.githubusercontent.com/304450/39149842-5d019296-4738-11e8-9c10-b8c203dce340.png)|![simulator screen shot - iphone 6s - 2018-04-23 at 18 46 18](https://user-images.githubusercontent.com/304450/39149848-6015c704-4738-11e8-8828-c5c0dcfc0e74.png)|
Migrated `LoadingContainer` to styled components
> refactor: switch LoadingContainer to styled components

- src/components/notification-list-item.component.js
- src/notifications/screens/notifications.screen.js
| Related ticket?  | #667         |
---
We now only try to navigate to the issue if the `notification.subject.type` was either a `PullRequest` or an `Issue`.
We still need it to be clickable to mark the notification as read.
Also made a release notification display the accurate icon (tag).
Closes #667.
> fix(crash): don't navigate to issue if it's a release notification

- src/components/loading-indicators/loading-modal.component.js
---
|![simulator screen shot - iphone 6 - 2018-04-25 at 17 29 00](https://user-images.githubusercontent.com/304450/39259580-ae637c40-48ae-11e8-9727-11f3b587be3d.png)|![simulator screen shot - iphone 6 - 2018-04-25 at 17 30 54](https://user-images.githubusercontent.com/304450/39259581-ae872ffa-48ae-11e8-84ca-62a3125c5228.png)|
Migrated LoadingModal to SC
> refactor(styled-components): migrate LoadingModal

- src/components/loading-indicators/loading-user-list-item.component.js
---
|![simulator screen shot - iphone 6 - 2018-04-25 at 17 22 58](https://user-images.githubusercontent.com/304450/39259210-c676f79a-48ad-11e8-890d-1d47e40ac41d.png)|![simulator screen shot - iphone 6 - 2018-04-25 at 17 23 18](https://user-images.githubusercontent.com/304450/39259212-c6b1d8e2-48ad-11e8-887e-e90cabaa0ced.png)|
Migrated LoadingUserListItem to SC
> refactor(styled-components): migrate LoadingUserListItem

- src/components/loading-indicators/loading-list-item.component.js
---
|![simulator screen shot - iphone 6 - 2018-04-25 at 17 01 41](https://user-images.githubusercontent.com/304450/39258504-046a150c-48ac-11e8-9396-a7569196cd4f.png)|![simulator screen shot - iphone 6 - 2018-04-25 at 17 02 24](https://user-images.githubusercontent.com/304450/39258505-04903cc8-48ac-11e8-91a0-082421f28b74.png)|
Migrated LoadingListItem to SC
> refactor(styled-components): migrate LoadingListItem

- src/components/comment-input.component.js
- src/components/image-zoom.component.js
- src/components/loading-indicators/loading-members-list.component.js
- src/components/loading-indicators/loading-repository-list-item.component.js
- src/components/loading-indicators/loading-repository-profile.component.js
- src/components/mention-area.component.js
- src/components/parallax-scroll.component.js
- src/components/toggle-view.component.js
- src/issue/screens/new-issue.screen.js
- src/issue/screens/pull-merge.screen.js
- src/notifications/screens/notifications.screen.js
- src/repository/screens/issue-list.screen.js
- src/repository/screens/pull-list.screen.js
- src/repository/screens/repository-file.screen.js
- src/search/screens/search.screen.js
- src/user/screens/repository-list.screen.js
- src/utils/loading-animation.js
| Devices tested?  | iPhone 7... |
---
As in [67a17a](https://github.com/gitpoint/git-point/commit/67a17aedec6195f36997cb24431ae2a72f10a01b), the react components doesn't pass props to super call, which results in TypeError if we need to use props in constructor.
From official [react document](https://reactjs.org/docs/state-and-lifecycle.html#adding-local-state-to-a-class): `Class components should always call the base constructor with props`.  This PR enforces all class components in project to follow this guideline, to avoid …
> fix: pass props into super() in constructor function

- __tests__/tests/utilities/migration-helper.js
Hey,
There are a few tests for Migration Helper.
> Add test for Migration Helper (#518)

- __tests__/tests/reducers/user.reducer.js
- src/user/user.reducer.js
#518
| Version?         | -     |
| Devices tested?  | - |
| Related ticket?  | #518        |
---
None
Add tests for user reducer.
> test(user.reducer): Add tests for user reducer

- __tests__/tests/components/GithubHtmlView.js
- __tests__/tests/components/github-htmlview.js
- src/components/github-htmlview.component.js
- src/components/toggle-view.component.js
| Devices tested?  | iPhone X |
| Related ticket?  | #528   |
---
Before (not support details tag)
After 1 (detail not expanded)
After 2 (detail expanded)
Support `<details>` tag in `GithubHtmlView`, as mentioned in #528 .
First try to find `<summary>` tag inside `<details>`, then render a toggle-able view if found, otherwise do a rollback rendering. Also try to prettify the text in `<summary>` if we got only one text child inside it.
Thanks!
> feat: support <details> tag for GithubHtmlView (#528)

- App.js
- ios/GitPoint.xcodeproj/project.pbxproj
- package.json
- root.store.js
- yarn.lock
| Devices tested?  | iPhone 7, Onplus 5 |
---
> Upgrade redux persist

- src/components/issue-list-item.component.js
- src/repository/screens/pull-list.screen.js
| Version?         | v1.6.0    |
| Related ticket?  | -        |
---
|![prlist-old](https://user-images.githubusercontent.com/1736154/48669177-caa0d000-eb39-11e8-8063-bdeada2fff0f.png)|![prlist-new](https://user-images.githubusercontent.com/1736154/48669176-caa0d000-eb39-11e8-838d-a4757a7e9726.png)|
Closed should include merged, too.
> fix(pr): show merged pull requests

- yarn.lock
Due to the author changed his/her account name, the hash was different. But I checked the downloaded zip, which has the same content and md5.
> chore: update lock hash

- __tests__/data/screens.js
- __tests__/tests/others/normalize-text.js
- src/config/normalize-text.js
Thanks to the initial work in #598 by @andrewda. This PR uses the same device list and test cases.
And,
- Fixes screens data by,
- https://www.mydevice.io/
- https://material.io/resources/devices/
- https://google.com
- Uses the great [jest.isolateModules(fn)](https://jestjs.io/docs/en/jest-object#jestisolatemodulesfn) to simulate different devices without resetting all mocked modules
- Updates to consider pixelRatio as intervals
- In fact, `normalize-text.js` was copyed from [react-native-elements/react-native-elements@v1.2.6](https://github.com/react-native-elements/react-native-elements/blob/v1.2.6/src/helpers/normalizeText.js
). So this is a sync operation.
Note that not all code branches are tested. I don't know how @andrewda finds those test devices. Maybe they are the most popular …
> test: add tests for normalize-text.js
